# Generated by Django 5.2.3 on 2025-07-24 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_coupon_order_orderitem'),
        ('user', '0003_alter_product_price_alter_product_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product', 'color')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
