# Generated by Django 5.2.3 on 2025-07-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cartitem_unique_together_remove_orderitem_size_and_more'),
    ]

    operations = [
    ]
