# Generated by Django 5.2.3 on 2025-07-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_merge_duplicate_cart_items'),
    ]

    operations = [
    ]
