# Generated by Django 5.1.5 on 2025-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merge_duplicate_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_per_piece_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_pieces_in_set_at_purchase',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
