# Generated by Django 5.1.5 on 2025-10-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_price_per_piece_at_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The final amount paid by the customer.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_label_url',
            field=models.URLField(blank=True, default=None, help_text='URL to the shipping label PDF', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_name',
            field=models.CharField(blank=True, default=None, help_text='e.g., Delhivery, XpressBees', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of products before discount and shipping.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default=None, help_text='AWB Number from the courier', max_length=100, null=True),
        ),
    ]
