# Generated by Django 5.1.5 on 2025-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_total_amount_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='The Razorpay Order ID (order_...)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='The Razorpay Payment ID (pay_...)', max_length=100, null=True),
        ),
    ]
