# Generated by Django 5.1.5 on 2026-08-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_status_order_payment_status_and_more'),
        ('user', '0011_alter_productimage_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Select products for which this coupon is valid.', to='user.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_product_specific',
            field=models.BooleanField(default=False, help_text='If checked, this coupon only applies to selected products.'),
        ),
    ]
