# Generated by Django 5.1.5 on 2025-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('template', models.CharField(choices=[('template1', 'Template 1'), ('template2', 'Template 2'), ('template3', 'Template 3'), ('template4', 'Template 4')], max_length=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('subtitle_1', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle_2', models.CharField(blank=True, max_length=300, null=True)),
                ('paragraph_1', models.TextField(blank=True, null=True)),
                ('paragraph_2', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
