# Generated by Django 5.1.5 on 2026-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_blogcategory_blogtag_blog_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='template',
        ),
        migrations.AddField(
            model_name='blog',
            name='html_content',
            field=models.TextField(blank=True, help_text='Paste your raw HTML here.', null=True),
        ),
    ]
