# Generated by Django 5.2.3 on 2025-07-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for one full set.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(help_text='Description of sizes in the set (e.g., 1S, 1M, 1L, 1XL)', max_length=255),
        ),
    ]
