# Generated by Django 5.2.3 on 2025-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_product_price_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price for one full set.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(help_text="Composition of sizes in the set (e.g., '1S, 2M, 1L, 1XL'). This determines the total pieces in one set.", max_length=255),
        ),
    ]
