# Generated by Django 5.2.3 on 2025-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_product_discount_price_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, help_text='Image shown on hover.', null=True, upload_to='products/hover/'),
        ),
    ]
