# Generated by Django 5.1.5 on 2025-10-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_course_coursepdf_coursevideo_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=10.0, help_text='Height of the packaged set in centimeters (cm).'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=30.0, help_text='Length of the packaged set in centimeters (cm).'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.5, help_text='Weight of the packaged set in kilograms (kg).'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=20.0, help_text='Width of the packaged set in centimeters (cm).'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(help_text="Composition of sizes in the set (e.g., '1S, 2M, 1L, 1XL').", max_length=255),
        ),
    ]
