# Generated by Django 5.1.5 on 2025-10-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_product_height_product_length_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of available SETS for this color.'),
        ),
    ]
