# Generated by Django 5.1.5 on 2025-10-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_productcolor_stock'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productcolor',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_must_be_positive'),
        ),
    ]
