# Generated by Django 5.1.5 on 2026-01-22 12:31

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_productcolor_stock_must_be_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, help_text="SEO text for category image (e.g., 'Summer Collection T-Shirts')", max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='hover_image_alt',
            field=models.CharField(blank=True, help_text='SEO alt text for hover image', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_image_alt',
            field=models.CharField(blank=True, help_text='SEO alt text for main image', max_length=160),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='SEO alt text for this specific color variant', max_length=160),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=user.models.get_category_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_product_hover_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(default=30.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(upload_to=user.models.get_product_primary_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(help_text="Composition: e.g., '1S, 2M, 1L'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='hex_code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=user.models.get_variant_image_path),
        ),
    ]
