# Generated by Django 5.1.5 on 2026-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_category_image_alt_product_hover_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='SEO alt text for variant image', max_length=160),
        ),
    ]
